name: dockerbuild

on:
  push:
    branches:
      - 'main'
permissions:
  id-token: write
  packages: write
  

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v1

      
      - name: Build with Maven
        run: mvn clean package --file pom.xml -DskipTests

      - name: generate tag
        run: |-
          export PROJ_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Project Version: $PROJ_VERSION"
          echo "TAG=$PROJ_VERSION-$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          echo "SHORT_TAG=$PROJ_VERSION" >> $GITHUB_ENV

      
      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.OU_REG_USER }}
          password: ${{ secrets.OU_REG_PASSWORD }}

      
      
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: src/main/docker/Dockerfile
          context: /home/runner/work/openunison-kubernetes-operator/openunison-kubernetes-operator
          tags: |
            docker.io/${{ secrets.OU_CONTAINER_REPO }}/openunison-kubernetes-operator:${{ env.TAG }}
            docker.io/${{ secrets.OU_CONTAINER_REPO }}/openunison-kubernetes-operator:${{ env.SHORT_TAG }}
            docker.io/${{ secrets.OU_CONTAINER_REPO }}/openunison-kubernetes-operator:latest

            ghcr.io/${{ env.REPO }}:${{ env.TAG }}
            ghcr.io/${{ env.REPO }}:${{ env.SHORT_TAG }}
            ghcr.io/${{ env.REPO }}:latest


      - name: sign images
        run: |-
          cosign sign -y ghcr.io/${{ env.REPO }}:${{ env.TAG }}

      
      - uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ env.REPO }}:${{ env.TAG }}
          format: spdx
          output-file: /tmp/spdxg

      - name: attach sbom to images
        run: |-
          cosign attach sbom --sbom /tmp/spdxg ghcr.io/${{ env.REPO }}:${{ env.TAG }}
          GH_SBOM_SHA=$(cosign verify --certificate-oidc-issuer-regexp='.*' --certificate-identity-regexp='.*' ghcr.io/${{ env.REPO }}:${{ env.TAG }} 2>/dev/null | jq -r '.[0].critical.image["docker-manifest-digest"]' | cut -c 8-)
          cosign sign -y ghcr.io/${{ env.REPO }}:sha256-$GH_SBOM_SHA.sbom


      
      