name: dockerbuild

on:
  push:
    branches:
      - 'main'
permissions:
  id-token: write
  contents: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v1

      
      - name: Build with Maven
        run: mvn clean package --file pom.xml -DskipTests

      - name: generate tag
        run: |-
          export PROJ_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Project Version: $PROJ_VERSION"
          echo "TAG=$PROJ_VERSION-$GITHUB_SHA" >> $GITHUB_ENV

      
      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.OU_REG_USER }}
          password: ${{ secrets.OU_REG_PASSWORD }}

      
      
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: src/main/docker/Dockerfile
          context: /home/runner/work/openunison-kubernetes-operator/openunison-kubernetes-operator
          tags: |
            docker.io/${{ secrets.OU_CONTAINER_REPO }}/openunison-kubernetes-operator:latest
            docker.io/${{ secrets.OU_CONTAINER_REPO }}/openunison-kubernetes-operator:${{ env.TAG }}
            ghcr.io/${{ env.REPO }}:latest
            ghcr.io/${{ env.REPO }}:${{ env.TAG }}


      - name: sign images
        run: |-
          COSIGN_EXPERIMENTAL=1 cosign sign docker.io/${{ secrets.OU_CONTAINER_REPO }}/openunison-kubernetes-operator:${{ env.TAG }}
          COSIGN_EXPERIMENTAL=1 cosign sign ghcr.io/${{ env.REPO }}:${{ env.TAG }}

      
      